version: '3'
services:
  db_mysql_5:
    build: 
      context: ./mysql
      dockerfile: Dockerfile.5
    image: mysql-5
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: docker
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
    volumes:
      - .data/bd:/var/lib/mysql:rw
      - ./mysql/db:/docker-entrypoint-initdb.d:rw
    ports:
      - "3306:3306"